# Any args that will override argparse input
LipReg_lambda: 0

model:
  # model kwargs example
  hidden_dim: 512
  dropout: 0.1
  num_encoder_layers: 3
  num_cross_layers: 1

optim:
  type: Adam                # optim type
  lr: 1.0e-5                # optim lr
  betas: [ 0.9, 0.999 ]     # optim kwargs

scheduler:
  type: CosineAnnealingLR   # scheduler type
  eta_min: 1.0e-5           # scheduler kwargs

losses:
  loss: # loss name
    type: CrossEntropyLoss  # loss type
    label_smoothing: 0.1    # loss kwargs
